#!/usr/bin/python
#-*-python-*-
#
# Look-up and Conversion of Levels of Concern; LABB report format
# (c) 2012 Greg Benison
#
# This program is free software; you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation; either version 2 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program; if not, write to the Free Software
# Foundation, Inc., 59 Temple Place, Suite 330, Boston, MA  02111-1307  USA
#
#

import cgitb, cgi, re

cgitb.enable()

form=cgi.FieldStorage()

from loc.labb_brief   import LabbBrief
from loc.labb_summary import LabbSummary
from loc.labb_full    import LabbFull

if form.getvalue('full') == 'on':
    report=LabbFull(form=form)
elif form.getvalue('summary') == 'on':
    report=LabbSummary(form=form)
else:
    report=LabbBrief(form=form)

report.http_reply()

